name: Waka Readme

on:
  # schedule:
  #   # runs at 0:00 AM UTC
  #   - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TIMEZONE: false
          SHOW_LOC_CHART: false
          SHOW_PROJECTS: false
          #SHOW_UPDATED_DATE: false
          #SHOW_LINES_OF_CODE: false
          #SHOW_TOTAL_CODE_TIME: false
          #SHOW_PROFILE_VIEWS: false
          #SHOW_EDITORS: false
          #SHOW_SHORT_INFO: false
